blueprint:
  name: Sync Alarmo & Frient Keypad (No Code Arming)
  description: Synchronisation bidirectionnelle entre Alarmo et le clavier Frient KEYZB-110 avec option d'armement sans code.
  domain: automation
  input:
    alarm_panel:
      name: Alarmo Entity
      description: L'entité de l'alarme Alarmo.
      selector:
        entity:
          domain: alarm_control_panel
    keypad_ieee:
      name: Keypad IEEE Address / Topic
      description: "Le topic MQTT du clavier (ex: zigbee2mqtt/Clavier_Entree)"
    arm_without_code:
      name: Autoriser l'armement sans code
      description: Si activé, presser 'Away' ou 'Home' armera l'alarme immédiatement sans demander de code sur le clavier.
      default: false
      selector:
        boolean: {}

variables:
  # On récupère l'input pour l'utiliser dans les templates
  arm_without_code: !input arm_without_code
  alarm_panel: !input alarm_panel

trigger:
  - platform: state
    entity_id: !input alarm_panel
    id: "alarm_state_change"
  - platform: mqtt
    topic: !input keypad_ieee
    id: "keypad_action"

action:
  - choose:
      # --- SYNCHRO ALARMO VERS CLAVIER (LEDs) ---
      - conditions:
          - condition: trigger
            id: "alarm_state_change"
        sequence:
          - service: mqtt.publish
            data:
              topic: !input keypad_ieee
              payload: >
                {% set state = trigger.to_state.state %}
                {% if state == 'armed_away' %} {"arm_mode": {"mode": "arm_all_zones"}}
                {% elif state == 'armed_home' %} {"arm_mode": {"mode": "arm_day_zones"}}
                {% elif state == 'disarmed' %} {"arm_mode": {"mode": "disarm"}}
                {% elif state == 'pending' %} {"arm_mode": {"mode": "entry_delay"}}
                {% elif state == 'arming' %} {"arm_mode": {"mode": "exit_delay"}}
                {% endif %}

      # --- COMMANDE CLAVIER VERS ALARMO ---
      - conditions:
          - condition: trigger
            id: "keypad_action"
        sequence:
          - variables:
              action: "{{ trigger.payload_json.action }}"
              code: "{{ trigger.payload_json.action_code | default('') }}"
              transaction: "{{ trigger.payload_json.action_transaction }}"
          
          - choose:
              # CAS : ARMEMENT (Vérifie si on autorise sans code OU si un code est fourni)
              - conditions:
                  - condition: template
                    value_template: >
                      {{ action in ['arm_all_zones', 'arm_day_zones', 'arm_night_zones'] and 
                         (arm_without_code or code != '') }}
                sequence:
                  - service: mqtt.publish
                    data:
                      topic: !input keypad_ieee
                      payload: "{\"arm_mode\": {\"transaction\": {{transaction}}, \"mode\": \"{{action}}\"}}"
                  - service: >
                      {% if action == 'arm_all_zones' %} alarm_control_panel.alarm_arm_away
                      {% elif action == 'arm_day_zones' %} alarm_control_panel.alarm_arm_home
                      {% else %} alarm_control_panel.alarm_arm_night
                      {% endif %}
                    target:
                      entity_id: !input alarm_panel
                    data:
                      code: "{{ code }}"

              # CAS : DÉSARMEMENT (Code obligatoire)
              - conditions:
                  - condition: template
                    value_template: "{{ action == 'disarm' and code != '' }}"
                sequence:
                  - service: mqtt.publish
                    data:
                      topic: !input keypad_ieee
                      payload: "{\"arm_mode\": {\"transaction\": {{transaction}}, \"mode\": \"disarm\"}}"
                  - service: alarm_control_panel.alarm_disarm
                    target:
                      entity_id: !input alarm_panel
                    data:
                      code: "{{ code }}"

              # CAS : ERREUR / CODE VIDE SUR DÉSARMEMENT
              - conditions:
                  - condition: template
                    value_template: "{{ transaction is defined }}"
                sequence:
                  - service: mqtt.publish
                    data:
                      topic: !input keypad_ieee
                      payload: "{\"arm_mode\": {\"transaction\": {{transaction}}, \"mode\": \"invalid_code\"}}"
